# SPDX-License-Identifier: MPL-2.0
#
# Contents of this file are sourced from https://github.com/recaptime-dev/base-repo-setup/blob/main/.github/labels.yml
# DO NOT DIRECTLY EDIT THIS FILE IF OUTSIDE THE META REPOSITORY OR BASE-REPO-SETUP
# REPOSITORY TEMPLATE! Instead, submit patches against the repo itself OR in the
# org community health repo (.github) instead.
#
# This YAML is used to declaratively manage GitHub issue labels with @crazy-max's
# issue labels management GitHub Action (https://github.com/crazy-max/ghaction-github-labeler).
# We recommend synchorizing your copy of this file alongside the companion GH Actions
# workflow file if you used this repo as a template or adopting them if not yet set up.

# basics
- name: bug
  color: d73a4a
  description: Something isn't working
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: help wanted
  color: '008672'
  description: Extra attention is needed
- name: invalid
  color: e4e669
  description: This doesn't seem right
- name: question
  color: d876e3
  description: Further information is requested
- name: wontfix
  color: ffffff
  description: This will not be worked on

# review status
- name: review/queue
  color: "000000"
  description: Patch enqueued for review.
- name: review/pending-human-review-ai
  color: F48FB1
  description: Flagged for additional human review due to use of AI tools in this contribution.
- name: review/approved
  color: "15e012"
  description: Approved by code reviewers or automation tooling pending merge.

# CI/CD tooling
- name: dependencies
  color: 3094FF
  description: Dependency management, packages, lockfiles
- name: ci/github-actions
  color: "000000"
  description: Issues and pull requests relating to our GitHub Actions setup
- name: ci/gitlab-ci
  color: FC6D26
  description: Issues and pull requests relating to our GitLab CI setup

# Automation
- name: automations/dependabot
  color: 3094FF
  description: Pull requests generated by Dependabot for dependency management

# generative ai tooling
- name: automations/agentic-coding
  color: 4285F4
  description: Catch-all label for use of AI tools for coding and infra.
- name: ai/coderabbit
  color: ff570a
  description: This contribution involves use of autonomous agentic workflows via CodeRabbit.
- name: ai/google-gemini
  color: 7CACF8
  description: This contribution involves parts or entirety being assisted/generated by Google Gemini models.
- name: ai/google-antigravity
  color: A142F4
  description: This contribution involves use of autonomous agentic workflows via Google Antigravity
- name: ai/claude
  color: d97757
  description: This contribution involves parts or entirety being assisted/generated by Anthropic Claude models.
- name: ai/claude-code
  color: d97757
  description: This contribution involves use of autonomus agentic workflows via Claude Code.
