# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
title: "[general] <your issue title here>"
name: "Other/General requests"
description: Sample description
assignees:
  - RecapTimeBot
  - ajhalili2006
body:
  - type: checkboxes
    attributes:
      label: Preflight Checks
      options:
        - label: >-
            I have [searched through the issues](https://github.com/recaptime-dev/meta/blob/main/.github/ISSUE_TRACKER_USAGE.md)
            across the Recap Time Squad's projects here in GitHub and confirmed there are no duplicates.
          required: true
        - label: >-
            I agree to the [Recap Time Squd Community Code of Conduct](https://policies.recaptime.dev/code-of-conduct).
          required: true
  - type: textarea
    id: details
    attributes:
      label: About this issue
      description: Describe what this is all talking about here in depth.
    validations:
      required: true
  - type: textarea
    id: additional_resources
    attributes:
      label: Additional resources / Prior art
      description: Related issues, documentation, etc.